"""add screening_run and conjunction

Screening results, written by the screening worker. conjunction has no bare
P_c column by design: public element sets carry no covariance, so the only
probability stored is the maximum over a stated aspect ratio, NULL where the
2D model is not valid (RA-12 sections 6-7).

Revision ID: 370a19531826
Revises: b41c7e9a2d30
Create Date: 2026-09-27 13:16:59.746672

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "370a19531826"
down_revision: str | Sequence[str] | None = "b41c7e9a2d30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "screening_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("step_s", sa.Float(), nullable=False),
        sa.Column("reporting_distance_km", sa.Float(), nullable=False),
        sa.Column("hard_body_radius_km", sa.Float(), nullable=False),
        sa.Column("aspect_ratio", sa.Float(), nullable=False),
        sa.Column("objects_screened", sa.Integer(), nullable=False),
        sa.Column("objects_skipped", sa.Integer(), nullable=False),
        sa.Column("colocated_excluded", sa.Integer(), nullable=False),
        sa.Column("encounters", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conjunction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("primary_object_id", sa.Integer(), nullable=False),
        sa.Column("secondary_object_id", sa.Integer(), nullable=False),
        sa.Column("tca", sa.DateTime(timezone=True), nullable=False),
        sa.Column("miss_distance_km", sa.Float(), nullable=False),
        sa.Column("relative_speed_km_s", sa.Float(), nullable=False),
        sa.Column("maximum_pc", sa.Float(), nullable=True),
        sa.Column("pc_method", sa.String(length=16), nullable=True),
        sa.Column("dilution_sigma_km", sa.Float(), nullable=False),
        sa.Column("valid_2d", sa.Boolean(), nullable=False),
        sa.Column("validity_reason", sa.Text(), nullable=True),
        sa.Column("encounter_duration_s", sa.Float(), nullable=False),
        sa.Column("primary_epoch", sa.DateTime(timezone=True), nullable=False),
        sa.Column("secondary_epoch", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["primary_object_id"],
            ["space_object.id"],
        ),
        sa.ForeignKeyConstraint(["run_id"], ["screening_run.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["secondary_object_id"],
            ["space_object.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_conjunction_primary_tca", "conjunction", ["primary_object_id", "tca"], unique=False
    )
    op.create_index(op.f("ix_conjunction_run_id"), "conjunction", ["run_id"], unique=False)
    op.create_index(
        "ix_conjunction_secondary_tca", "conjunction", ["secondary_object_id", "tca"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_conjunction_secondary_tca", table_name="conjunction")
    op.drop_index(op.f("ix_conjunction_run_id"), table_name="conjunction")
    op.drop_index("ix_conjunction_primary_tca", table_name="conjunction")
    op.drop_table("conjunction")
    op.drop_table("screening_run")
    # ### end Alembic commands ###
