"""create space_object and element_set

Revision ID: 3932e767f3b9
Revises: 
Create Date: 2026-08-14 17:31:31.062435

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3932e767f3b9'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('space_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('norad_id', sa.String(length=16), nullable=False),
    sa.Column('intl_designator', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=True),
    sa.Column('operator', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('launch_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rcs_size', sa.String(length=16), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_space_object_norad_id'), 'space_object', ['norad_id'], unique=True)
    op.create_table('element_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('epoch', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mean_motion', sa.Float(), nullable=False),
    sa.Column('eccentricity', sa.Float(), nullable=False),
    sa.Column('inclination', sa.Float(), nullable=False),
    sa.Column('ra_of_asc_node', sa.Float(), nullable=False),
    sa.Column('arg_of_pericenter', sa.Float(), nullable=False),
    sa.Column('mean_anomaly', sa.Float(), nullable=False),
    sa.Column('bstar', sa.Float(), nullable=False),
    sa.Column('mean_motion_dot', sa.Float(), nullable=False),
    sa.Column('mean_motion_ddot', sa.Float(), nullable=False),
    sa.Column('ephemeris_type', sa.Integer(), nullable=False),
    sa.Column('classification_type', sa.String(length=1), nullable=False),
    sa.Column('element_set_no', sa.Integer(), nullable=False),
    sa.Column('rev_at_epoch', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_format', sa.String(length=16), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['space_object.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'ix_element_set_object_epoch', 'element_set', ['object_id', 'epoch'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_element_set_object_epoch', table_name='element_set')
    op.drop_table('element_set')
    op.drop_index(op.f('ix_space_object_norad_id'), table_name='space_object')
    op.drop_table('space_object')
    # ### end Alembic commands ###
