"""add satcat fields to space_object

Revision ID: 8d1f884cbe85
Revises: 3932e767f3b9
Create Date: 2026-09-15 11:23:34.509457

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d1f884cbe85"
down_revision: str | Sequence[str] | None = "3932e767f3b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("space_object", sa.Column("rcs", sa.Float(), nullable=True))
    op.add_column(
        "space_object", sa.Column("decay_date", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("space_object", sa.Column("ops_status_code", sa.String(length=4), nullable=True))
    op.add_column("space_object", sa.Column("data_status_code", sa.String(length=4), nullable=True))
    op.add_column("space_object", sa.Column("launch_site", sa.String(length=16), nullable=True))
    op.add_column(
        "space_object",
        sa.Column("analyst", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column("space_object", sa.Column("satcat_source", sa.String(length=32), nullable=True))
    op.add_column(
        "space_object", sa.Column("satcat_updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("space_object", "satcat_updated_at")
    op.drop_column("space_object", "satcat_source")
    op.drop_column("space_object", "analyst")
    op.drop_column("space_object", "launch_site")
    op.drop_column("space_object", "data_status_code")
    op.drop_column("space_object", "ops_status_code")
    op.drop_column("space_object", "decay_date")
    op.drop_column("space_object", "rcs")
    # ### end Alembic commands ###
